plugins {
    // 查看 https://fabricmc.net/develop/ 获取新版本
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false
    // 查看 https://projects.neoforged.net/neoforged/moddevgradle 获取新版本
    id 'net.neoforged.moddev' version '2.0.141' apply false

    id 'com.gradleup.shadow' version '8.3.6' apply false
}

allprojects {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }

        mavenCentral()

        maven {
            name = "isXander Maven"
            url = "https://maven.isxander.dev/releases"
        }

        maven {
            name = "Shedaniel Maven"
            url = "https://maven.shedaniel.me/"
        }

        maven {
            name = "Modrinth"
            url = "https://api.modrinth.com/maven"
        }

        maven {
            name = "TerraformersMC"
            url = "https://maven.terraformersmc.com/releases/"
            content {
                includeGroup "com.terraformersmc"
            }
        }
    }
}

subprojects { subproject ->
    subproject.plugins.withType(JavaPlugin) {
        subproject.dependencies {
            implementation "org.yaml:snakeyaml:${project.snakeyaml_version}"
        }
    }

    if (subproject.name == 'fabric' || subproject.name == 'neoforge') {
        def targetOutputDir = rootProject.layout.projectDirectory.dir("target/${project.version}-mc${project.minecraft_version}")

        // 配置所有打包任务的输出文件名
        subproject.tasks.matching {
            it.name in ['jar', 'remapJar', 'sourcesJar', 'remapSourcesJar', 'javadocJar', 'shadowJar']
        }.configureEach { task ->
            def suffix = ''
            if (task.name in ['sourcesJar', 'remapSourcesJar']) suffix = '-sources'
            else if (task.name == 'javadocJar') suffix = '-javadoc'
            archiveFileName = "${project.mod_id}-${project.version}+mc${project.minecraft_version}-${subproject.name}${suffix}.jar"
            destinationDirectory = targetOutputDir
        }
    }
}