# 重要提示:
# 您添加的每个字段都必须同时添加到 buildSrc/src/main/groovy/multiloader-common.gradle 的 expandProps 映射中.

# 项目
version=3.1
group=com.dearxuan.easyhopper
java_version=25

# 通用
minecraft_version=1.21.11
mod_name=EasyHopper
mod_author=DearXuan
mod_id=easyhopper
license=MIT License
credits=
description=EasyHopper gives your hoppers more powerful features.
minecraft_version_range=[1.21.11, 26.1)

## 这是 'common' 项目使用的 Minecraft 版本, 你可以在以下网址找到所有版本的列表
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
## ParchmentMC 版本, 查看 https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Fabric, 查看 https://fabricmc.net/develop/ 获取新版本
fabric_version=0.141.6+1.21.11
fabric_loader_version=0.19.3

# NeoForge, 查看 https://projects.neoforged.net/neoforged/neoforge 获取新版本
neoforge_version=21.11.45
neoforge_loader_version_range=[4,)

# 组件
## 双端 YACL 版本, 自动加上后缀: https://modrinth.com/mod/yacl/versions?l=fabric&l=neoforge
yacl_version=3.8.2+1.21.11
## 双端 Cloth Config API 版本: https://modrinth.com/mod/cloth-config/versions?l=fabric&l=neoforge
cloth_config_version=21.11.153
## Fabric 端 ModMenu: https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=17.0.0
## snakeyaml 版本: https://central.sonatype.com/artifact/org.yaml/snakeyaml
snakeyaml_version=2.6
## quilt-parsers 版本, 与 YACL 内嵌版本保持一致. 开发运行环境中 Loom 不会加载 YACL 的内嵌包, 需要额外提供
quilt_parsers_version=0.2.1
## cloth-basic-math 版本, 与 ClothConfig 内嵌版本保持一致
cloth_basic_math_version=0.6.1
## TwelveMonkeys ImageIO 版本, 与 YACL 内嵌版本保持一致 (用于加载 WebP 图标)
twelvemonkeys_version=3.12.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
