# 重要提示:
# 您添加的每个字段都必须同时添加到 buildSrc/src/main/groovy/multiloader-common.gradle 的 expandProps 映射中.

# 项目
version=3.0
group=com.dearxuan.easyhopper
java_version=25

# 通用
minecraft_version=26.2
mod_name=EasyHopper
mod_author=DearXuan
mod_id=easyhopper
license=MIT License
credits=
description=EasyHopper gives your hoppers more powerful features.
minecraft_version_range=[26.2, 26.3)

## 这是 'common' 项目使用的 Minecraft 版本, 您可以在以下网址找到所有版本的列表
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric, 查看 https://fabricmc.net/develop/ 获取新版本
fabric_version=0.155.2+26.2
fabric_loader_version=0.19.3

# NeoForge, 查看 https://projects.neoforged.net/neoforged/neoforge 获取新版本
neoforge_version=26.2.0.28-beta
neoforge_loader_version_range=[4,)

# 组件
## 双端 YACL 版本, 自动加上后缀: https://modrinth.com/mod/yacl/versions?l=fabric&l=neoforge
yacl_version=3.9.6+26.2
## 双端 Cloth Config API 版本: https://modrinth.com/mod/cloth-config/versions?l=fabric&l=neoforge
cloth_config_version=26.2.155
## Fabric 端 ModMenu: https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=20.0.1
## snakeyaml 版本: https://central.sonatype.com/artifact/org.yaml/snakeyaml
snakeyaml_version=2.6

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false