# \u91CD\u8981\u63D0\u793A:
# \u60A8\u6DFB\u52A0\u7684\u6BCF\u4E2A\u5B57\u6BB5\u90FD\u5FC5\u987B\u540C\u65F6\u6DFB\u52A0\u5230 buildSrc/src/main/groovy/multiloader-common.gradle \u7684 expandProps \u6620\u5C04\u4E2D.

# \u9879\u76EE
version=3.1
group=com.dearxuan.easyhopper
java_version=25

# \u901A\u7528
minecraft_version=26.2
mod_name=EasyHopper
mod_author=DearXuan
mod_id=easyhopper
license=MIT License
credits=
description=EasyHopper gives your hoppers more powerful features.
minecraft_version_range=[26.2, 26.3)

## \u8FD9\u662F 'common' \u9879\u76EE\u4F7F\u7528\u7684 Minecraft \u7248\u672C, \u60A8\u53EF\u4EE5\u5728\u4EE5\u4E0B\u7F51\u5740\u627E\u5230\u6240\u6709\u7248\u672C\u7684\u5217\u8868
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric, \u67E5\u770B https://fabricmc.net/develop/ \u83B7\u53D6\u65B0\u7248\u672C
fabric_version=0.155.2+26.2
fabric_loader_version=0.19.3

# NeoForge, \u67E5\u770B https://projects.neoforged.net/neoforged/neoforge \u83B7\u53D6\u65B0\u7248\u672C
neoforge_version=26.2.0.28-beta
neoforge_loader_version_range=[4,)

# \u7EC4\u4EF6
## \u53CC\u7AEF YACL \u7248\u672C, \u81EA\u52A8\u52A0\u4E0A\u540E\u7F00: https://modrinth.com/mod/yacl/versions?l=fabric&l=neoforge
yacl_version=3.9.6+26.2
## \u53CC\u7AEF Cloth Config API \u7248\u672C: https://modrinth.com/mod/cloth-config/versions?l=fabric&l=neoforge
cloth_config_version=26.2.155
## Fabric \u7AEF ModMenu: https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu_version=20.0.1
## snakeyaml \u7248\u672C: https://central.sonatype.com/artifact/org.yaml/snakeyaml
snakeyaml_version=2.6

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false