modLoader = "javafml" # 必填
loaderVersion = "${neoforge_loader_version_range}" # 必填
license = "${license}" # 在 https://choosealicense.com/ 查看您的选项.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" # 可选
[[mods]] # 必填
modId = "${mod_id}" # 必填
version = "${version}+mc${minecraft_version}-neoforge" # 必填
displayName = "${mod_name}" # 必填
#updateJSONURL="https://change.me.example.invalid/updates.json" # 可选 (参见 https://docs.neoforged.net/docs/misc/updatechecker/) 
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" # 可选 (在模组 UI 中显示) 
logoFile="${mod_id}.png" # 可选
credits="${credits}" # 可选
authors = "${mod_author}" # 可选
description = '''${description}''' # 必填 (支持多行文本) 
[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"
[[dependencies.${mod_id}]] # 可选
modId = "neoforge" # 必填
type="required" # 必填 (可以是 "required", "optional", "incompatible" 或 "discouraged") 
versionRange = "[${neoforge_version},)" # 必填
ordering = "NONE" # 此依赖项相对于您的模组的加载顺序, 如果依赖项不是必需的, 则需要设置为 'BEFORE' 或 'AFTER'
side = "BOTH" # 此依赖项应用的端 - 'BOTH', 'CLIENT' 或 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required" # 必填 (可以是 "required", "optional", "incompatible" 或 "discouraged") 
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

# Features 是游戏环境的特定属性, 您可能想要声明您需要它们. 此示例声明您的模组需要 GL 3.2 或更高版本.
# 未来还会添加其他 Features. 它们具有端感知能力, 因此声明此项不会阻止您的模组在服务器上加载.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
